import bpy,json,ast,hashlib,struct
from pathlib import Path
P=Path('D:/UnityProj/Proj_Recon/Art/ElseIf_Blockout_20260922/MobileVR_20260926');report={}
for cn in ['ElseIf_Game_Backup','ElseIf_Game_Optimized','ElseIf_Game_MobileVR_Test']:
 c=bpy.data.collections[cn];meshes=[o for o in c.objects if o.type=='MESH'];bones={b.name for o in c.objects if o.type=='ARMATURE' for b in o.data.bones};mats={m for o in meshes for m in o.data.materials if m};tex={n.image for m in mats if m.use_nodes for n in m.node_tree.nodes if n.type=='TEX_IMAGE' and n.image};keys=[k for o in meshes if o.data.shape_keys for k in o.data.shape_keys.key_blocks if k!=o.data.shape_keys.reference_key];report[cn]={'vertices':sum(len(o.data.vertices) for o in meshes),'triangles':sum(sum(len(f.vertices)-2 for f in o.data.polygons) for o in meshes),'mesh_objects':len(meshes),'skinned_mesh_objects':sum(any(m.type=='ARMATURE' for m in o.modifiers) for o in meshes),'material_slots':sum(len(o.data.materials) for o in meshes),'materials':len(mats),'textures':len(tex),'bones':len(bones),'max_bone_influence':max(sum(g.weight>1e-6 and o.vertex_groups[g.group].name in bones for g in v.groups) for o in meshes for v in o.data.vertices),'shape_keys_without_basis':len(keys),'shape_key_names':len({k.name for k in keys}),'shape_keys_with_basis':sum(len(o.data.shape_keys.key_blocks) for o in meshes if o.data.shape_keys),'mesh_details':[{'name':o.name,'triangles':sum(len(f.vertices)-2 for f in o.data.polygons),'materials':len(o.data.materials)} for o in meshes]}
src=(P.parent/'DesignTransfer_20260924/07_preserve_recover.py').read_text(encoding='utf-8-sig');fn=next(n for n in ast.parse(src).body if isinstance(n,ast.FunctionDef) and n.name=='fp');exec(compile(ast.Module(body=[fn],type_ignores=[]),'<fp>','exec'))
for s in list(bpy.data.scenes):bpy.context.window.scene=s;bpy.context.view_layer.update()
before=json.loads((P/'Protected_Backup_Evaluated.json').read_text());changed=[n for n,p in before.items() if n not in bpy.data.objects or fp(bpy.data.objects[n])!=p];report['protected_original_changes']=changed;bpy.context.window.scene=bpy.data.scenes['ElseIf_MobileVR_Review'];(P/'Statistics.json').write_text(json.dumps(report,indent=2));print(json.dumps({n:{k:v for k,v in r.items() if k!='mesh_details'} if isinstance(r,dict) else r for n,r in report.items()}))

