import json
from pathlib import Path
P=Path('D:/UnityProj/Proj_Recon/Art/ElseIf_Blockout_20260922/MobileVR_20260926')
load=lambda n:json.loads((P/n).read_text(encoding='utf-8-sig'))
s=load('Statistics.json');fin=load('Final_Validation.json');initial=load('Initial_Inventory.json');tri=s['ElseIf_Game_MobileVR_Test']['triangles'];current=s['ElseIf_Game_Backup']['triangles'];optimized=s['ElseIf_Game_Optimized']['triangles'];keys=load('Shape_Key_Classification.json');stress=load('Stress_Audit.json');metrics=load('SmallView_Metrics.json')
lines=['# ElseIf MobileVR Test — LOD0候補','', '2026-09-26。Masterと承認済みGame/Optimizedを保持し、ElseIf_Game_MobileVR_Testのみを編集した。','',f'最終候補は **{tri:,} Triangles**。Current Gameから **{(1-tri/current)*100:.2f}%**、272,628 TrianglesのOptimizedから **{(1-tri/optimized)*100:.2f}%** 削減した。60k〜100kの目安は超えている。約104kの候補では袖口・裾の縁に256pxでも分かる乱れが発生したため、その部分を保護して118,656で停止した。','', '256px HighAngleでは全身、左右の腕、萌え袖、脚、靴の主要な外周と配色を維持している。布の陰影や縁の細部は完全一致ではない。Standalone実機での性能は未測定。','', '## 数値比較','', '| 項目 | Current Game | Optimized | MobileVR Test |','|---|---:|---:|---:|']
for label,k in [('Vertices','vertices'),('Triangles','triangles'),('Mesh','mesh_objects'),('Skinned Mesh','skinned_mesh_objects'),('Material Slots','material_slots'),('Materials','materials'),('Textures','textures'),('Bones','bones'),('最大Bone Influence','max_bone_influence'),('Shape Keys（Basis除外・配置総数）','shape_keys_without_basis')]:
 lines.append('| '+label+' | '+' | '.join(f'{s[n][k]:,}' for n in ['ElseIf_Game_Backup','ElseIf_Game_Optimized','ElseIf_Game_MobileVR_Test'])+' |')
lines+=['','CurrentのShape Keyは複数Objectへの重複配置を含む190個、名称種類は27個。MobileVRはJacket上の27個のみで、Basisを含めると28個。追加Boneは0。Humanoidの74 Bone名は元モデルと一致し、手指を含めSkeletonを保持した。','', '## 削減前：272,628 Trianglesの内訳','', '| Object | Vertices | Triangles | 割合 |','|---|---:|---:|---:|']
for r in sorted(initial['meshes'],key=lambda r:-r['triangles']):lines.append(f"| {r['name']} | {r['vertices']:,} | {r['triangles']:,} | {r['triangles']/optimized*100:.2f}% |")
lines+=['','ジャケットには縫製・マーキング・背面グラフィックなどの小部品も統合されている。人体はMannequinとAnatomy_Restorationの2Object。Restorationの大部分は上半身・首周辺の高密度な補完面で、脚全体ではない。','', '## 最終：Mesh別の内訳','', '| Object | Vertices | Triangles | 割合 | Material Slots |','|---|---:|---:|---:|---:|']
for r in fin['mesh_details']:lines.append(f"| {r['name']} | {r['vertices']:,} | {r['triangles']:,} | {r['triangles']/tri*100:.2f}% | {r['material_slots']} |")
lines+=['','実際に評価された描画MeshのTriangle数も上表と一致。未適用Subdivisionによる隠れた増加はない。人体2個、左右ソックス、左右靴をそれぞれ統合し、全12ポーズで統合前後の頂点位置差は0 mmだった。','', '## 削減方法と保持箇所','', '- Jacket：部品ごとの局所削減。肩・脇・肘・補正量の変化が大きい頂点と開口境界を優先保護。接触した16面には95頂点を局所的に追加し、補正とWeightを元モデルから転写した。','- 袖口・襟・裾・前開きの縁：位置を動かす削減を取り消し、元の部品から再構成。平坦に近い面の分割だけを整理した。対象48,406→23,766 Triangles。','- ソックス：左右37,518→8,368。靴：左右21,360→5,364。パンツ：13,128→3,356。関節・外周を優先した部位別削減。','- マーキング・背面画像・配色を保持。既存の画像Textureは1枚を埋め込み。小さな平面グラフィックは既に安価な形状のため、必要な面を残した。新しいNormal MapのベイクやAtlas制作は行っていない。','- Materialは10種類を保持。統合可能な同一Material Slotを整理して29→20。無理な1 Material化はしていない。','', '## 人体隠面と安全マージン','', '| 人体 | Triangles |','|---|---:|','| Current Game | 43,544 |','| 今回開始時Optimized | 36,505 |','| MobileVR Test | 35,345 |','',f'今回追加削除：1,160 Triangles（開始時人体から{1160/36505*100:.2f}%）。Currentから累計8,199 Triangles、{8199/43544*100:.2f}%削減。','', '胸・腹側の衣服内部、および残存人体に重なる補完面のうち、テストポーズで隠れると判定できた面を削除した。境界に露出候補が出た箇所には4 Edge Loop分の余裕を戻した。手・指・首周辺と開口部の安全域は保持。腕・脚・足などは前工程の削除状態を引き継いだが、今回すべての残存面を一括削除したわけではない。確実性を確認できない上半身の補完面は保守的に残している。','', '全12ポーズで新しい削除境界の端点・中点を26方向から検査し、露出候補0。これは有限のポーズ・方向に対する検査結果であり、あらゆる将来ポーズを保証するものではない。','', '## Shape Key / Weight','', '27個すべてに非ゼロの変形、ドライバー、テスト中の作動を確認した。肘の体積補正2、手首・萌え袖補正4、肩・脇8、その他のポーズ接触補正13。今回不要と確定できたキーはなく、全27個を保持した。キー別の分類は Shape_Key_Classification.json に記録。','', '最大Bone Influenceは4。無ウェイト頂点0、ウェイト合計誤差は最大0.000092未満。全補正ドライバーの対象はElseIf_MobileVR_Humanoid。最終Unity Export時のドライバー移行は未実施。','', '## ストレステスト','', '| Pose | Jacket / 人体交差ペア | 状態 |','|---|---:|---|']
for p,r in stress.items():
 count=sum(v.get('Jacket',0) for v in r['Mobile__']['intersections'].values());note='検出0' if not count else '補完人体との内部接触が残る（元モデルも6ペア）';lines.append(f'| {p} | {count} | {note} |')
lines+=['','指定7ポーズ（Base、Natural、ArmsWide、AsymmetricAim、Elbow90、OneArmBack、WristTwist）はJacket/人体交差0。追加のI_FrontBackだけ12交差ペアが残る。これを全ポーズ完全無交差とは扱わない。ソックス・パンツと内部人体の重なりも元モデルから存在し、MobileVRでも検出されるため、モデル全体の交差数0を主張しない。','', '手指は1,528頂点をHighAngle/BackQuarterから全12ポーズで確認し、見えるサンプル0。人工的に袖口を閉じた判定用Meshでは不安定な検出があったため、その値を露出判定の結論には用いていない。比較レンダーでも手指の新しい露出は確認できなかった。','', '元Jacketに対する三角形中心の距離は95パーセンタイル0.45〜0.53 mm。最大値はポーズによって4.75〜31.76 mmで、一部の大きな面には差が残る。数値は元部品表面への片方向距離であり、完全一致の証明ではない。','', '## 比較画像','', '同一カメラ・照明・ポーズ、880×1120、Cycles 48 samples。Current/Optimizedの前工程画像を再利用し、MobileVRを同条件で描画。Small Viewは各ポーズ共通の切り出し範囲でキャラクター長辺256px。','',f"![256px比較]({(P/'SmallView_256_Comparison.jpg').as_posix()})",'', '通常サイズ比較：']
for n in ['Base_HighAngle','Natural_HighAngle','ArmsWide','AsymmetricAim','Elbow90','OneArmBack','WristTwist','Base_BackQuarter']:lines.append(f"- [{n}]({(P/('Compare_'+n+'.jpg')).as_posix()})")
lines+=['','256px比較のOptimized→MobileVR平均RGB絶対差は1.03〜2.41/255。陰影・アンチエイリアスを含むため知覚上の一致を意味しない。主要外周・配色は維持される一方、近距離の布面の陰影差、背面裾の細部差は残る。','', '## 保護・保存・停止範囲','', 'Protected_Backup_Evaluated.jsonとの照合で既存原本の変更0件。Master、承認済みGame、Optimized、既存Shape Keyを保持。工程フォルダの原本とバックアップは移動せず保存した。Art/Latestには完成原本をコピーし、SHA256照合結果をLatest_Copy_Verification.jsonへ記録する。','', 'LOD1/LOD2、Unity Export、Humanoid Avatar設定、実機性能測定、Texture Atlas最終化には進んでいない。118,656 TrianglesのMobileVR LOD0候補と比較結果をもって停止する。','', '主な検証記録：Statistics.json、Final_Validation.json、Final_Merge_Equivalence.json、Stress_Audit.json、Boundary_Visibility_Final.json、Hand_Camera_Visibility.json、Shape_Key_Classification.json、SmallView_Metrics.json。']
(P/'REPORT.md').write_text('\n'.join(lines)+'\n',encoding='utf-8');(P/'Reduction_Summary.json').write_text(json.dumps({'triangles':tri,'reduction_from_current_percent':(1-tri/current)*100,'reduction_from_optimized_percent':(1-tri/optimized)*100,'body_before':36505,'body_after':35345,'body_deleted':1160,'target_range':[60000,100000],'target_reached':False,'reason':'Opening and hem quality protection after visible artifacts in ~104k candidate'},indent=2));print('REPORT.md written')
