//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/App/Script/Common/Inputs/GameMaininput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/App/Script/Common/Inputs/GameMaininput.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @GameMaininput: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @GameMaininput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameMaininput"",
    ""maps"": [
        {
            ""name"": ""Main"",
            ""id"": ""bfd741a3-106b-4b67-a164-70fe0153d005"",
            ""actions"": [
                {
                    ""name"": ""LeftStickAxis"",
                    ""type"": ""Value"",
                    ""id"": ""255d1e97-f1b5-4402-a929-0f1ed57eb976"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightStickAxis"",
                    ""type"": ""Value"",
                    ""id"": ""acec7ded-47c8-4163-b39e-0c6bd7ed5b63"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GrabRight"",
                    ""type"": ""Button"",
                    ""id"": ""f40b17ce-4522-4256-ac78-11c969a482bb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GrabLeft"",
                    ""type"": ""Button"",
                    ""id"": ""88b80192-d84b-4d3c-aa03-e05aa51837c7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseRight"",
                    ""type"": ""Button"",
                    ""id"": ""e80f48df-fb8d-4e5d-bfaf-340beecadb69"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseLeft"",
                    ""type"": ""Button"",
                    ""id"": ""38d80a65-8675-4f34-bb90-21638e626c13"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightPrimary"",
                    ""type"": ""Button"",
                    ""id"": ""998735b2-44a0-4165-b927-bb98ef127463"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightSecondary"",
                    ""type"": ""Button"",
                    ""id"": ""bccdd6a3-c557-46fc-b908-24a94f25d71d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftPrimary"",
                    ""type"": ""Button"",
                    ""id"": ""e1c6e9e4-9bc2-4963-bf61-a46234416e4c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftSecondary"",
                    ""type"": ""Button"",
                    ""id"": ""e5f5796c-c05c-4567-b9bc-8a7c6401a305"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PushRightStick"",
                    ""type"": ""Button"",
                    ""id"": ""593cae1b-cb4b-4bd4-b2dc-79e7685e9f5a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PushLeftStick"",
                    ""type"": ""Button"",
                    ""id"": ""9ecaa068-1128-48e9-8c43-d3b8d266a3c7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse"",
                    ""type"": ""Button"",
                    ""id"": ""fc921513-1ae6-4a14-bf57-2a3482cfd089"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FocusLeftSwitch"",
                    ""type"": ""Button"",
                    ""id"": ""67086733-cfd8-45bc-b7c8-12b4e316c5f1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FocusRightSwitch"",
                    ""type"": ""Button"",
                    ""id"": ""805b61f9-56e2-4511-83a0-4ab04640e751"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FocusLeftHold"",
                    ""type"": ""Button"",
                    ""id"": ""4e821823-2d0c-43cd-9af7-0818ce919159"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FocusRightHold"",
                    ""type"": ""Button"",
                    ""id"": ""ec49d8fc-a398-4e20-8547-d5f552c44ce7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dodge"",
                    ""type"": ""Button"",
                    ""id"": ""01f65260-408f-4f93-a097-88577778a6e2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ebecdece-1cf6-4f69-a5ce-7fd18b7d7123"",
                    ""path"": ""<XRController>{LeftHand}/joystick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""96ab09ab-6ec3-4d6f-b93c-13d4c0026ab9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c88cc3d9-9ac6-48b4-b848-e7989da5d7b8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1d26285e-3a23-454d-87d0-ea0616f3a4b9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""246e49b8-1253-4022-9191-7917724785fd"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""353dc30a-c75c-43d0-bef0-1472d62bd200"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5d4c1249-63de-4ebe-aab5-a40f38a31a28"",
                    ""path"": ""<XRController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fcbad545-1124-4f20-81c0-2176041a92e4"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0613a715-abd6-40ca-bd55-563d0b2ff7d4"",
                    ""path"": ""<XRController>{LeftHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4d4da07-80cb-4734-89b4-aa78cb3e97dd"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0f44adc-7111-4c06-8998-f4eea59b8b89"",
                    ""path"": ""<XRController>{RightHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0ff3102-13fe-425d-8f29-3cf50c424294"",
                    ""path"": ""<XRController>{LeftHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""52254d96-a454-452b-a45e-ef63d04d02b2"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25cfaa53-c8ed-469a-9e3f-1d0e8e6440a1"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightSecondary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9fe60d2-aed6-4263-854d-843aecb6b016"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightSecondary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7dd05ae7-d6f3-4970-9404-05549028ba0b"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPrimary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b8ce233-0695-4f3a-9e9d-11e7ddb46081"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPrimary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59d3cdd6-877b-4c40-95ef-042f2a5eed4d"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPrimary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b1ad5ce-4464-4d3a-b9a9-e4a0400743e6"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPrimary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9558fbb1-1607-45be-b4b9-0a8afd4d4eb8"",
                    ""path"": ""<XRController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftSecondary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f41a6a09-2141-4daf-a1e2-e29c55e26a2e"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftSecondary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""499a8c6a-8879-443b-a36d-39d569217636"",
                    ""path"": ""<XRController>{RightHand}/{Primary2DAxisClick}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PushRightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3bafe61-a932-41cf-9d7a-d8957457cf7b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PushRightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e303da18-9eda-42a2-b348-546d936c76c7"",
                    ""path"": ""<XRController>{LeftHand}/{Secondary2DAxisClick}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PushLeftStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d955bd0-0f0b-4ffa-a2b5-ff2d9138eff6"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PushLeftStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8336e717-f095-4008-a574-753261df75f0"",
                    ""path"": ""<XRController>{RightHand}/joystick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""a2906c56-84a8-465b-8762-2433d56c0e37"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4f0a68c1-e5dd-438a-a0b1-d0e60ee68677"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5de391ba-ddb7-4756-ab09-c41deea3470a"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1aa5ed0e-9484-4b8e-972d-a7aa7f5dfd2a"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e28f514d-d917-4eb4-891c-2880566bac52"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""da17e376-8b93-4fa1-96db-eeca43de3ec1"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1e65263-096f-4dd9-9787-98bc5aa86f36"",
                    ""path"": ""<XRController>{LeftHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FocusLeftSwitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf4684d3-aeba-46f1-a3a8-5e1e3a2a77d6"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FocusLeftSwitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c4353b7-f9d4-4e04-8bae-0b3f97c8ba72"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FocusRightSwitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42a27024-49fa-4dd1-86f5-d6c6494fa65f"",
                    ""path"": ""<XRController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FocusRightSwitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b8f9563-ca42-4cc5-b732-3e66e2dc60bd"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FocusLeftHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd812fc0-9349-40a1-9976-37fa61f9faa7"",
                    ""path"": ""<XRController>{LeftHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FocusLeftHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a2db633-df64-4cf4-9a80-e90343a2dca5"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FocusRightHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f0fb887-7b56-4415-8deb-378d7bff7506"",
                    ""path"": ""<XRController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FocusRightHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""efc1146e-1abe-4fbf-918f-001127cbff9a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f1f3628-09da-4ce8-9144-945ff0b3ed3c"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Debug"",
            ""id"": ""161f24ed-c71f-400a-936d-2de2e4c360e0"",
            ""actions"": [
                {
                    ""name"": ""ShotModeNormal"",
                    ""type"": ""Button"",
                    ""id"": ""0bb98e8d-f5f3-4f0a-bd4a-0434988d5be5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShotModeWaltz"",
                    ""type"": ""Button"",
                    ""id"": ""f823978c-f983-43a0-a9a6-5a54f0f129ae"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShotModeMerge"",
                    ""type"": ""Button"",
                    ""id"": ""a8ee643b-6d89-4bcd-83f7-a2664a22b003"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""286353dc-a301-42d9-865e-48feb8c6517f"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShotModeNormal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7837609-31d8-4c49-bea3-b7b382c1aa43"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShotModeWaltz"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff100718-9919-47fb-b8bb-de930df7b4cd"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShotModeMerge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Main
        m_Main = asset.FindActionMap("Main", throwIfNotFound: true);
        m_Main_LeftStickAxis = m_Main.FindAction("LeftStickAxis", throwIfNotFound: true);
        m_Main_RightStickAxis = m_Main.FindAction("RightStickAxis", throwIfNotFound: true);
        m_Main_GrabRight = m_Main.FindAction("GrabRight", throwIfNotFound: true);
        m_Main_GrabLeft = m_Main.FindAction("GrabLeft", throwIfNotFound: true);
        m_Main_UseRight = m_Main.FindAction("UseRight", throwIfNotFound: true);
        m_Main_UseLeft = m_Main.FindAction("UseLeft", throwIfNotFound: true);
        m_Main_RightPrimary = m_Main.FindAction("RightPrimary", throwIfNotFound: true);
        m_Main_RightSecondary = m_Main.FindAction("RightSecondary", throwIfNotFound: true);
        m_Main_LeftPrimary = m_Main.FindAction("LeftPrimary", throwIfNotFound: true);
        m_Main_LeftSecondary = m_Main.FindAction("LeftSecondary", throwIfNotFound: true);
        m_Main_PushRightStick = m_Main.FindAction("PushRightStick", throwIfNotFound: true);
        m_Main_PushLeftStick = m_Main.FindAction("PushLeftStick", throwIfNotFound: true);
        m_Main_Mouse = m_Main.FindAction("Mouse", throwIfNotFound: true);
        m_Main_FocusLeftSwitch = m_Main.FindAction("FocusLeftSwitch", throwIfNotFound: true);
        m_Main_FocusRightSwitch = m_Main.FindAction("FocusRightSwitch", throwIfNotFound: true);
        m_Main_FocusLeftHold = m_Main.FindAction("FocusLeftHold", throwIfNotFound: true);
        m_Main_FocusRightHold = m_Main.FindAction("FocusRightHold", throwIfNotFound: true);
        m_Main_Dodge = m_Main.FindAction("Dodge", throwIfNotFound: true);
        // Debug
        m_Debug = asset.FindActionMap("Debug", throwIfNotFound: true);
        m_Debug_ShotModeNormal = m_Debug.FindAction("ShotModeNormal", throwIfNotFound: true);
        m_Debug_ShotModeWaltz = m_Debug.FindAction("ShotModeWaltz", throwIfNotFound: true);
        m_Debug_ShotModeMerge = m_Debug.FindAction("ShotModeMerge", throwIfNotFound: true);
    }

    ~@GameMaininput()
    {
        UnityEngine.Debug.Assert(!m_Main.enabled, "This will cause a leak and performance issues, GameMaininput.Main.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Debug.enabled, "This will cause a leak and performance issues, GameMaininput.Debug.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Main
    private readonly InputActionMap m_Main;
    private List<IMainActions> m_MainActionsCallbackInterfaces = new List<IMainActions>();
    private readonly InputAction m_Main_LeftStickAxis;
    private readonly InputAction m_Main_RightStickAxis;
    private readonly InputAction m_Main_GrabRight;
    private readonly InputAction m_Main_GrabLeft;
    private readonly InputAction m_Main_UseRight;
    private readonly InputAction m_Main_UseLeft;
    private readonly InputAction m_Main_RightPrimary;
    private readonly InputAction m_Main_RightSecondary;
    private readonly InputAction m_Main_LeftPrimary;
    private readonly InputAction m_Main_LeftSecondary;
    private readonly InputAction m_Main_PushRightStick;
    private readonly InputAction m_Main_PushLeftStick;
    private readonly InputAction m_Main_Mouse;
    private readonly InputAction m_Main_FocusLeftSwitch;
    private readonly InputAction m_Main_FocusRightSwitch;
    private readonly InputAction m_Main_FocusLeftHold;
    private readonly InputAction m_Main_FocusRightHold;
    private readonly InputAction m_Main_Dodge;
    /// <summary>
    /// Provides access to input actions defined in input action map "Main".
    /// </summary>
    public struct MainActions
    {
        private @GameMaininput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public MainActions(@GameMaininput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Main/LeftStickAxis".
        /// </summary>
        public InputAction @LeftStickAxis => m_Wrapper.m_Main_LeftStickAxis;
        /// <summary>
        /// Provides access to the underlying input action "Main/RightStickAxis".
        /// </summary>
        public InputAction @RightStickAxis => m_Wrapper.m_Main_RightStickAxis;
        /// <summary>
        /// Provides access to the underlying input action "Main/GrabRight".
        /// </summary>
        public InputAction @GrabRight => m_Wrapper.m_Main_GrabRight;
        /// <summary>
        /// Provides access to the underlying input action "Main/GrabLeft".
        /// </summary>
        public InputAction @GrabLeft => m_Wrapper.m_Main_GrabLeft;
        /// <summary>
        /// Provides access to the underlying input action "Main/UseRight".
        /// </summary>
        public InputAction @UseRight => m_Wrapper.m_Main_UseRight;
        /// <summary>
        /// Provides access to the underlying input action "Main/UseLeft".
        /// </summary>
        public InputAction @UseLeft => m_Wrapper.m_Main_UseLeft;
        /// <summary>
        /// Provides access to the underlying input action "Main/RightPrimary".
        /// </summary>
        public InputAction @RightPrimary => m_Wrapper.m_Main_RightPrimary;
        /// <summary>
        /// Provides access to the underlying input action "Main/RightSecondary".
        /// </summary>
        public InputAction @RightSecondary => m_Wrapper.m_Main_RightSecondary;
        /// <summary>
        /// Provides access to the underlying input action "Main/LeftPrimary".
        /// </summary>
        public InputAction @LeftPrimary => m_Wrapper.m_Main_LeftPrimary;
        /// <summary>
        /// Provides access to the underlying input action "Main/LeftSecondary".
        /// </summary>
        public InputAction @LeftSecondary => m_Wrapper.m_Main_LeftSecondary;
        /// <summary>
        /// Provides access to the underlying input action "Main/PushRightStick".
        /// </summary>
        public InputAction @PushRightStick => m_Wrapper.m_Main_PushRightStick;
        /// <summary>
        /// Provides access to the underlying input action "Main/PushLeftStick".
        /// </summary>
        public InputAction @PushLeftStick => m_Wrapper.m_Main_PushLeftStick;
        /// <summary>
        /// Provides access to the underlying input action "Main/Mouse".
        /// </summary>
        public InputAction @Mouse => m_Wrapper.m_Main_Mouse;
        /// <summary>
        /// Provides access to the underlying input action "Main/FocusLeftSwitch".
        /// </summary>
        public InputAction @FocusLeftSwitch => m_Wrapper.m_Main_FocusLeftSwitch;
        /// <summary>
        /// Provides access to the underlying input action "Main/FocusRightSwitch".
        /// </summary>
        public InputAction @FocusRightSwitch => m_Wrapper.m_Main_FocusRightSwitch;
        /// <summary>
        /// Provides access to the underlying input action "Main/FocusLeftHold".
        /// </summary>
        public InputAction @FocusLeftHold => m_Wrapper.m_Main_FocusLeftHold;
        /// <summary>
        /// Provides access to the underlying input action "Main/FocusRightHold".
        /// </summary>
        public InputAction @FocusRightHold => m_Wrapper.m_Main_FocusRightHold;
        /// <summary>
        /// Provides access to the underlying input action "Main/Dodge".
        /// </summary>
        public InputAction @Dodge => m_Wrapper.m_Main_Dodge;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Main; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="MainActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(MainActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="MainActions" />
        public void AddCallbacks(IMainActions instance)
        {
            if (instance == null || m_Wrapper.m_MainActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MainActionsCallbackInterfaces.Add(instance);
            @LeftStickAxis.started += instance.OnLeftStickAxis;
            @LeftStickAxis.performed += instance.OnLeftStickAxis;
            @LeftStickAxis.canceled += instance.OnLeftStickAxis;
            @RightStickAxis.started += instance.OnRightStickAxis;
            @RightStickAxis.performed += instance.OnRightStickAxis;
            @RightStickAxis.canceled += instance.OnRightStickAxis;
            @GrabRight.started += instance.OnGrabRight;
            @GrabRight.performed += instance.OnGrabRight;
            @GrabRight.canceled += instance.OnGrabRight;
            @GrabLeft.started += instance.OnGrabLeft;
            @GrabLeft.performed += instance.OnGrabLeft;
            @GrabLeft.canceled += instance.OnGrabLeft;
            @UseRight.started += instance.OnUseRight;
            @UseRight.performed += instance.OnUseRight;
            @UseRight.canceled += instance.OnUseRight;
            @UseLeft.started += instance.OnUseLeft;
            @UseLeft.performed += instance.OnUseLeft;
            @UseLeft.canceled += instance.OnUseLeft;
            @RightPrimary.started += instance.OnRightPrimary;
            @RightPrimary.performed += instance.OnRightPrimary;
            @RightPrimary.canceled += instance.OnRightPrimary;
            @RightSecondary.started += instance.OnRightSecondary;
            @RightSecondary.performed += instance.OnRightSecondary;
            @RightSecondary.canceled += instance.OnRightSecondary;
            @LeftPrimary.started += instance.OnLeftPrimary;
            @LeftPrimary.performed += instance.OnLeftPrimary;
            @LeftPrimary.canceled += instance.OnLeftPrimary;
            @LeftSecondary.started += instance.OnLeftSecondary;
            @LeftSecondary.performed += instance.OnLeftSecondary;
            @LeftSecondary.canceled += instance.OnLeftSecondary;
            @PushRightStick.started += instance.OnPushRightStick;
            @PushRightStick.performed += instance.OnPushRightStick;
            @PushRightStick.canceled += instance.OnPushRightStick;
            @PushLeftStick.started += instance.OnPushLeftStick;
            @PushLeftStick.performed += instance.OnPushLeftStick;
            @PushLeftStick.canceled += instance.OnPushLeftStick;
            @Mouse.started += instance.OnMouse;
            @Mouse.performed += instance.OnMouse;
            @Mouse.canceled += instance.OnMouse;
            @FocusLeftSwitch.started += instance.OnFocusLeftSwitch;
            @FocusLeftSwitch.performed += instance.OnFocusLeftSwitch;
            @FocusLeftSwitch.canceled += instance.OnFocusLeftSwitch;
            @FocusRightSwitch.started += instance.OnFocusRightSwitch;
            @FocusRightSwitch.performed += instance.OnFocusRightSwitch;
            @FocusRightSwitch.canceled += instance.OnFocusRightSwitch;
            @FocusLeftHold.started += instance.OnFocusLeftHold;
            @FocusLeftHold.performed += instance.OnFocusLeftHold;
            @FocusLeftHold.canceled += instance.OnFocusLeftHold;
            @FocusRightHold.started += instance.OnFocusRightHold;
            @FocusRightHold.performed += instance.OnFocusRightHold;
            @FocusRightHold.canceled += instance.OnFocusRightHold;
            @Dodge.started += instance.OnDodge;
            @Dodge.performed += instance.OnDodge;
            @Dodge.canceled += instance.OnDodge;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="MainActions" />
        private void UnregisterCallbacks(IMainActions instance)
        {
            @LeftStickAxis.started -= instance.OnLeftStickAxis;
            @LeftStickAxis.performed -= instance.OnLeftStickAxis;
            @LeftStickAxis.canceled -= instance.OnLeftStickAxis;
            @RightStickAxis.started -= instance.OnRightStickAxis;
            @RightStickAxis.performed -= instance.OnRightStickAxis;
            @RightStickAxis.canceled -= instance.OnRightStickAxis;
            @GrabRight.started -= instance.OnGrabRight;
            @GrabRight.performed -= instance.OnGrabRight;
            @GrabRight.canceled -= instance.OnGrabRight;
            @GrabLeft.started -= instance.OnGrabLeft;
            @GrabLeft.performed -= instance.OnGrabLeft;
            @GrabLeft.canceled -= instance.OnGrabLeft;
            @UseRight.started -= instance.OnUseRight;
            @UseRight.performed -= instance.OnUseRight;
            @UseRight.canceled -= instance.OnUseRight;
            @UseLeft.started -= instance.OnUseLeft;
            @UseLeft.performed -= instance.OnUseLeft;
            @UseLeft.canceled -= instance.OnUseLeft;
            @RightPrimary.started -= instance.OnRightPrimary;
            @RightPrimary.performed -= instance.OnRightPrimary;
            @RightPrimary.canceled -= instance.OnRightPrimary;
            @RightSecondary.started -= instance.OnRightSecondary;
            @RightSecondary.performed -= instance.OnRightSecondary;
            @RightSecondary.canceled -= instance.OnRightSecondary;
            @LeftPrimary.started -= instance.OnLeftPrimary;
            @LeftPrimary.performed -= instance.OnLeftPrimary;
            @LeftPrimary.canceled -= instance.OnLeftPrimary;
            @LeftSecondary.started -= instance.OnLeftSecondary;
            @LeftSecondary.performed -= instance.OnLeftSecondary;
            @LeftSecondary.canceled -= instance.OnLeftSecondary;
            @PushRightStick.started -= instance.OnPushRightStick;
            @PushRightStick.performed -= instance.OnPushRightStick;
            @PushRightStick.canceled -= instance.OnPushRightStick;
            @PushLeftStick.started -= instance.OnPushLeftStick;
            @PushLeftStick.performed -= instance.OnPushLeftStick;
            @PushLeftStick.canceled -= instance.OnPushLeftStick;
            @Mouse.started -= instance.OnMouse;
            @Mouse.performed -= instance.OnMouse;
            @Mouse.canceled -= instance.OnMouse;
            @FocusLeftSwitch.started -= instance.OnFocusLeftSwitch;
            @FocusLeftSwitch.performed -= instance.OnFocusLeftSwitch;
            @FocusLeftSwitch.canceled -= instance.OnFocusLeftSwitch;
            @FocusRightSwitch.started -= instance.OnFocusRightSwitch;
            @FocusRightSwitch.performed -= instance.OnFocusRightSwitch;
            @FocusRightSwitch.canceled -= instance.OnFocusRightSwitch;
            @FocusLeftHold.started -= instance.OnFocusLeftHold;
            @FocusLeftHold.performed -= instance.OnFocusLeftHold;
            @FocusLeftHold.canceled -= instance.OnFocusLeftHold;
            @FocusRightHold.started -= instance.OnFocusRightHold;
            @FocusRightHold.performed -= instance.OnFocusRightHold;
            @FocusRightHold.canceled -= instance.OnFocusRightHold;
            @Dodge.started -= instance.OnDodge;
            @Dodge.performed -= instance.OnDodge;
            @Dodge.canceled -= instance.OnDodge;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="MainActions.UnregisterCallbacks(IMainActions)" />.
        /// </summary>
        /// <seealso cref="MainActions.UnregisterCallbacks(IMainActions)" />
        public void RemoveCallbacks(IMainActions instance)
        {
            if (m_Wrapper.m_MainActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="MainActions.AddCallbacks(IMainActions)" />
        /// <seealso cref="MainActions.RemoveCallbacks(IMainActions)" />
        /// <seealso cref="MainActions.UnregisterCallbacks(IMainActions)" />
        public void SetCallbacks(IMainActions instance)
        {
            foreach (var item in m_Wrapper.m_MainActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MainActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="MainActions" /> instance referencing this action map.
    /// </summary>
    public MainActions @Main => new MainActions(this);

    // Debug
    private readonly InputActionMap m_Debug;
    private List<IDebugActions> m_DebugActionsCallbackInterfaces = new List<IDebugActions>();
    private readonly InputAction m_Debug_ShotModeNormal;
    private readonly InputAction m_Debug_ShotModeWaltz;
    private readonly InputAction m_Debug_ShotModeMerge;
    /// <summary>
    /// Provides access to input actions defined in input action map "Debug".
    /// </summary>
    public struct DebugActions
    {
        private @GameMaininput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public DebugActions(@GameMaininput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Debug/ShotModeNormal".
        /// </summary>
        public InputAction @ShotModeNormal => m_Wrapper.m_Debug_ShotModeNormal;
        /// <summary>
        /// Provides access to the underlying input action "Debug/ShotModeWaltz".
        /// </summary>
        public InputAction @ShotModeWaltz => m_Wrapper.m_Debug_ShotModeWaltz;
        /// <summary>
        /// Provides access to the underlying input action "Debug/ShotModeMerge".
        /// </summary>
        public InputAction @ShotModeMerge => m_Wrapper.m_Debug_ShotModeMerge;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Debug; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="DebugActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(DebugActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="DebugActions" />
        public void AddCallbacks(IDebugActions instance)
        {
            if (instance == null || m_Wrapper.m_DebugActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DebugActionsCallbackInterfaces.Add(instance);
            @ShotModeNormal.started += instance.OnShotModeNormal;
            @ShotModeNormal.performed += instance.OnShotModeNormal;
            @ShotModeNormal.canceled += instance.OnShotModeNormal;
            @ShotModeWaltz.started += instance.OnShotModeWaltz;
            @ShotModeWaltz.performed += instance.OnShotModeWaltz;
            @ShotModeWaltz.canceled += instance.OnShotModeWaltz;
            @ShotModeMerge.started += instance.OnShotModeMerge;
            @ShotModeMerge.performed += instance.OnShotModeMerge;
            @ShotModeMerge.canceled += instance.OnShotModeMerge;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="DebugActions" />
        private void UnregisterCallbacks(IDebugActions instance)
        {
            @ShotModeNormal.started -= instance.OnShotModeNormal;
            @ShotModeNormal.performed -= instance.OnShotModeNormal;
            @ShotModeNormal.canceled -= instance.OnShotModeNormal;
            @ShotModeWaltz.started -= instance.OnShotModeWaltz;
            @ShotModeWaltz.performed -= instance.OnShotModeWaltz;
            @ShotModeWaltz.canceled -= instance.OnShotModeWaltz;
            @ShotModeMerge.started -= instance.OnShotModeMerge;
            @ShotModeMerge.performed -= instance.OnShotModeMerge;
            @ShotModeMerge.canceled -= instance.OnShotModeMerge;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="DebugActions.UnregisterCallbacks(IDebugActions)" />.
        /// </summary>
        /// <seealso cref="DebugActions.UnregisterCallbacks(IDebugActions)" />
        public void RemoveCallbacks(IDebugActions instance)
        {
            if (m_Wrapper.m_DebugActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="DebugActions.AddCallbacks(IDebugActions)" />
        /// <seealso cref="DebugActions.RemoveCallbacks(IDebugActions)" />
        /// <seealso cref="DebugActions.UnregisterCallbacks(IDebugActions)" />
        public void SetCallbacks(IDebugActions instance)
        {
            foreach (var item in m_Wrapper.m_DebugActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DebugActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="DebugActions" /> instance referencing this action map.
    /// </summary>
    public DebugActions @Debug => new DebugActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Main" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="MainActions.AddCallbacks(IMainActions)" />
    /// <seealso cref="MainActions.RemoveCallbacks(IMainActions)" />
    public interface IMainActions
    {
        /// <summary>
        /// Method invoked when associated input action "LeftStickAxis" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftStickAxis(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightStickAxis" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightStickAxis(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "GrabRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGrabRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "GrabLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGrabLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightPrimary" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightPrimary(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightSecondary" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightSecondary(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftPrimary" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftPrimary(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftSecondary" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftSecondary(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PushRightStick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPushRightStick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PushLeftStick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPushLeftStick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Mouse" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMouse(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "FocusLeftSwitch" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFocusLeftSwitch(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "FocusRightSwitch" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFocusRightSwitch(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "FocusLeftHold" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFocusLeftHold(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "FocusRightHold" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFocusRightHold(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Dodge" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDodge(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Debug" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="DebugActions.AddCallbacks(IDebugActions)" />
    /// <seealso cref="DebugActions.RemoveCallbacks(IDebugActions)" />
    public interface IDebugActions
    {
        /// <summary>
        /// Method invoked when associated input action "ShotModeNormal" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnShotModeNormal(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ShotModeWaltz" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnShotModeWaltz(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ShotModeMerge" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnShotModeMerge(InputAction.CallbackContext context);
    }
}
