//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/App/Script/Common/Inputs/GameMaininput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameMaininput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameMaininput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameMaininput"",
    ""maps"": [
        {
            ""name"": ""Main"",
            ""id"": ""bfd741a3-106b-4b67-a164-70fe0153d005"",
            ""actions"": [
                {
                    ""name"": ""LeftStickAxis"",
                    ""type"": ""Value"",
                    ""id"": ""255d1e97-f1b5-4402-a929-0f1ed57eb976"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightStickAxis"",
                    ""type"": ""Value"",
                    ""id"": ""acec7ded-47c8-4163-b39e-0c6bd7ed5b63"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GrabRight"",
                    ""type"": ""Button"",
                    ""id"": ""f40b17ce-4522-4256-ac78-11c969a482bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GrabLeft"",
                    ""type"": ""Button"",
                    ""id"": ""88b80192-d84b-4d3c-aa03-e05aa51837c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseRight"",
                    ""type"": ""Button"",
                    ""id"": ""e80f48df-fb8d-4e5d-bfaf-340beecadb69"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseLeft"",
                    ""type"": ""Button"",
                    ""id"": ""38d80a65-8675-4f34-bb90-21638e626c13"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightPrimary"",
                    ""type"": ""Button"",
                    ""id"": ""998735b2-44a0-4165-b927-bb98ef127463"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightSecondary"",
                    ""type"": ""Button"",
                    ""id"": ""bccdd6a3-c557-46fc-b908-24a94f25d71d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftPrimary"",
                    ""type"": ""Button"",
                    ""id"": ""e1c6e9e4-9bc2-4963-bf61-a46234416e4c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftSecondary"",
                    ""type"": ""Button"",
                    ""id"": ""e5f5796c-c05c-4567-b9bc-8a7c6401a305"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PushRightStick"",
                    ""type"": ""Button"",
                    ""id"": ""593cae1b-cb4b-4bd4-b2dc-79e7685e9f5a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PushLeftStick"",
                    ""type"": ""Button"",
                    ""id"": ""9ecaa068-1128-48e9-8c43-d3b8d266a3c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse"",
                    ""type"": ""Button"",
                    ""id"": ""fc921513-1ae6-4a14-bf57-2a3482cfd089"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ebecdece-1cf6-4f69-a5ce-7fd18b7d7123"",
                    ""path"": ""<XRController>{LeftHand}/joystick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""96ab09ab-6ec3-4d6f-b93c-13d4c0026ab9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c88cc3d9-9ac6-48b4-b848-e7989da5d7b8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1d26285e-3a23-454d-87d0-ea0616f3a4b9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""246e49b8-1253-4022-9191-7917724785fd"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""353dc30a-c75c-43d0-bef0-1472d62bd200"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5d4c1249-63de-4ebe-aab5-a40f38a31a28"",
                    ""path"": ""<XRController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fcbad545-1124-4f20-81c0-2176041a92e4"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0613a715-abd6-40ca-bd55-563d0b2ff7d4"",
                    ""path"": ""<XRController>{LeftHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9423ff5-36f3-4faf-abd0-cf34cc10b85d"",
                    ""path"": ""<Mouse>/backButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0f44adc-7111-4c06-8998-f4eea59b8b89"",
                    ""path"": ""<XRController>{RightHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""52254d96-a454-452b-a45e-ef63d04d02b2"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0ff3102-13fe-425d-8f29-3cf50c424294"",
                    ""path"": ""<XRController>{LeftHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3fbae58d-ca4e-4ce4-a963-c2a655e254b4"",
                    ""path"": ""<Mouse>/forwardButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25cfaa53-c8ed-469a-9e3f-1d0e8e6440a1"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightSecondary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9fe60d2-aed6-4263-854d-843aecb6b016"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightSecondary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7dd05ae7-d6f3-4970-9404-05549028ba0b"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPrimary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b8ce233-0695-4f3a-9e9d-11e7ddb46081"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPrimary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59d3cdd6-877b-4c40-95ef-042f2a5eed4d"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPrimary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b1ad5ce-4464-4d3a-b9a9-e4a0400743e6"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPrimary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9558fbb1-1607-45be-b4b9-0a8afd4d4eb8"",
                    ""path"": ""<XRController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftSecondary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f41a6a09-2141-4daf-a1e2-e29c55e26a2e"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftSecondary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""499a8c6a-8879-443b-a36d-39d569217636"",
                    ""path"": ""<XRController>{RightHand}/{Primary2DAxisClick}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PushRightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3bafe61-a932-41cf-9d7a-d8957457cf7b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PushRightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e303da18-9eda-42a2-b348-546d936c76c7"",
                    ""path"": ""<XRController>{LeftHand}/{Secondary2DAxisClick}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PushLeftStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d955bd0-0f0b-4ffa-a2b5-ff2d9138eff6"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PushLeftStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8336e717-f095-4008-a574-753261df75f0"",
                    ""path"": ""<XRController>{RightHand}/joystick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""a2906c56-84a8-465b-8762-2433d56c0e37"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4f0a68c1-e5dd-438a-a0b1-d0e60ee68677"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5de391ba-ddb7-4756-ab09-c41deea3470a"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1aa5ed0e-9484-4b8e-972d-a7aa7f5dfd2a"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e28f514d-d917-4eb4-891c-2880566bac52"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""da17e376-8b93-4fa1-96db-eeca43de3ec1"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Main
        m_Main = asset.FindActionMap("Main", throwIfNotFound: true);
        m_Main_LeftStickAxis = m_Main.FindAction("LeftStickAxis", throwIfNotFound: true);
        m_Main_RightStickAxis = m_Main.FindAction("RightStickAxis", throwIfNotFound: true);
        m_Main_GrabRight = m_Main.FindAction("GrabRight", throwIfNotFound: true);
        m_Main_GrabLeft = m_Main.FindAction("GrabLeft", throwIfNotFound: true);
        m_Main_UseRight = m_Main.FindAction("UseRight", throwIfNotFound: true);
        m_Main_UseLeft = m_Main.FindAction("UseLeft", throwIfNotFound: true);
        m_Main_RightPrimary = m_Main.FindAction("RightPrimary", throwIfNotFound: true);
        m_Main_RightSecondary = m_Main.FindAction("RightSecondary", throwIfNotFound: true);
        m_Main_LeftPrimary = m_Main.FindAction("LeftPrimary", throwIfNotFound: true);
        m_Main_LeftSecondary = m_Main.FindAction("LeftSecondary", throwIfNotFound: true);
        m_Main_PushRightStick = m_Main.FindAction("PushRightStick", throwIfNotFound: true);
        m_Main_PushLeftStick = m_Main.FindAction("PushLeftStick", throwIfNotFound: true);
        m_Main_Mouse = m_Main.FindAction("Mouse", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Main
    private readonly InputActionMap m_Main;
    private List<IMainActions> m_MainActionsCallbackInterfaces = new List<IMainActions>();
    private readonly InputAction m_Main_LeftStickAxis;
    private readonly InputAction m_Main_RightStickAxis;
    private readonly InputAction m_Main_GrabRight;
    private readonly InputAction m_Main_GrabLeft;
    private readonly InputAction m_Main_UseRight;
    private readonly InputAction m_Main_UseLeft;
    private readonly InputAction m_Main_RightPrimary;
    private readonly InputAction m_Main_RightSecondary;
    private readonly InputAction m_Main_LeftPrimary;
    private readonly InputAction m_Main_LeftSecondary;
    private readonly InputAction m_Main_PushRightStick;
    private readonly InputAction m_Main_PushLeftStick;
    private readonly InputAction m_Main_Mouse;
    public struct MainActions
    {
        private @GameMaininput m_Wrapper;
        public MainActions(@GameMaininput wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftStickAxis => m_Wrapper.m_Main_LeftStickAxis;
        public InputAction @RightStickAxis => m_Wrapper.m_Main_RightStickAxis;
        public InputAction @GrabRight => m_Wrapper.m_Main_GrabRight;
        public InputAction @GrabLeft => m_Wrapper.m_Main_GrabLeft;
        public InputAction @UseRight => m_Wrapper.m_Main_UseRight;
        public InputAction @UseLeft => m_Wrapper.m_Main_UseLeft;
        public InputAction @RightPrimary => m_Wrapper.m_Main_RightPrimary;
        public InputAction @RightSecondary => m_Wrapper.m_Main_RightSecondary;
        public InputAction @LeftPrimary => m_Wrapper.m_Main_LeftPrimary;
        public InputAction @LeftSecondary => m_Wrapper.m_Main_LeftSecondary;
        public InputAction @PushRightStick => m_Wrapper.m_Main_PushRightStick;
        public InputAction @PushLeftStick => m_Wrapper.m_Main_PushLeftStick;
        public InputAction @Mouse => m_Wrapper.m_Main_Mouse;
        public InputActionMap Get() { return m_Wrapper.m_Main; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainActions set) { return set.Get(); }
        public void AddCallbacks(IMainActions instance)
        {
            if (instance == null || m_Wrapper.m_MainActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MainActionsCallbackInterfaces.Add(instance);
            @LeftStickAxis.started += instance.OnLeftStickAxis;
            @LeftStickAxis.performed += instance.OnLeftStickAxis;
            @LeftStickAxis.canceled += instance.OnLeftStickAxis;
            @RightStickAxis.started += instance.OnRightStickAxis;
            @RightStickAxis.performed += instance.OnRightStickAxis;
            @RightStickAxis.canceled += instance.OnRightStickAxis;
            @GrabRight.started += instance.OnGrabRight;
            @GrabRight.performed += instance.OnGrabRight;
            @GrabRight.canceled += instance.OnGrabRight;
            @GrabLeft.started += instance.OnGrabLeft;
            @GrabLeft.performed += instance.OnGrabLeft;
            @GrabLeft.canceled += instance.OnGrabLeft;
            @UseRight.started += instance.OnUseRight;
            @UseRight.performed += instance.OnUseRight;
            @UseRight.canceled += instance.OnUseRight;
            @UseLeft.started += instance.OnUseLeft;
            @UseLeft.performed += instance.OnUseLeft;
            @UseLeft.canceled += instance.OnUseLeft;
            @RightPrimary.started += instance.OnRightPrimary;
            @RightPrimary.performed += instance.OnRightPrimary;
            @RightPrimary.canceled += instance.OnRightPrimary;
            @RightSecondary.started += instance.OnRightSecondary;
            @RightSecondary.performed += instance.OnRightSecondary;
            @RightSecondary.canceled += instance.OnRightSecondary;
            @LeftPrimary.started += instance.OnLeftPrimary;
            @LeftPrimary.performed += instance.OnLeftPrimary;
            @LeftPrimary.canceled += instance.OnLeftPrimary;
            @LeftSecondary.started += instance.OnLeftSecondary;
            @LeftSecondary.performed += instance.OnLeftSecondary;
            @LeftSecondary.canceled += instance.OnLeftSecondary;
            @PushRightStick.started += instance.OnPushRightStick;
            @PushRightStick.performed += instance.OnPushRightStick;
            @PushRightStick.canceled += instance.OnPushRightStick;
            @PushLeftStick.started += instance.OnPushLeftStick;
            @PushLeftStick.performed += instance.OnPushLeftStick;
            @PushLeftStick.canceled += instance.OnPushLeftStick;
            @Mouse.started += instance.OnMouse;
            @Mouse.performed += instance.OnMouse;
            @Mouse.canceled += instance.OnMouse;
        }

        private void UnregisterCallbacks(IMainActions instance)
        {
            @LeftStickAxis.started -= instance.OnLeftStickAxis;
            @LeftStickAxis.performed -= instance.OnLeftStickAxis;
            @LeftStickAxis.canceled -= instance.OnLeftStickAxis;
            @RightStickAxis.started -= instance.OnRightStickAxis;
            @RightStickAxis.performed -= instance.OnRightStickAxis;
            @RightStickAxis.canceled -= instance.OnRightStickAxis;
            @GrabRight.started -= instance.OnGrabRight;
            @GrabRight.performed -= instance.OnGrabRight;
            @GrabRight.canceled -= instance.OnGrabRight;
            @GrabLeft.started -= instance.OnGrabLeft;
            @GrabLeft.performed -= instance.OnGrabLeft;
            @GrabLeft.canceled -= instance.OnGrabLeft;
            @UseRight.started -= instance.OnUseRight;
            @UseRight.performed -= instance.OnUseRight;
            @UseRight.canceled -= instance.OnUseRight;
            @UseLeft.started -= instance.OnUseLeft;
            @UseLeft.performed -= instance.OnUseLeft;
            @UseLeft.canceled -= instance.OnUseLeft;
            @RightPrimary.started -= instance.OnRightPrimary;
            @RightPrimary.performed -= instance.OnRightPrimary;
            @RightPrimary.canceled -= instance.OnRightPrimary;
            @RightSecondary.started -= instance.OnRightSecondary;
            @RightSecondary.performed -= instance.OnRightSecondary;
            @RightSecondary.canceled -= instance.OnRightSecondary;
            @LeftPrimary.started -= instance.OnLeftPrimary;
            @LeftPrimary.performed -= instance.OnLeftPrimary;
            @LeftPrimary.canceled -= instance.OnLeftPrimary;
            @LeftSecondary.started -= instance.OnLeftSecondary;
            @LeftSecondary.performed -= instance.OnLeftSecondary;
            @LeftSecondary.canceled -= instance.OnLeftSecondary;
            @PushRightStick.started -= instance.OnPushRightStick;
            @PushRightStick.performed -= instance.OnPushRightStick;
            @PushRightStick.canceled -= instance.OnPushRightStick;
            @PushLeftStick.started -= instance.OnPushLeftStick;
            @PushLeftStick.performed -= instance.OnPushLeftStick;
            @PushLeftStick.canceled -= instance.OnPushLeftStick;
            @Mouse.started -= instance.OnMouse;
            @Mouse.performed -= instance.OnMouse;
            @Mouse.canceled -= instance.OnMouse;
        }

        public void RemoveCallbacks(IMainActions instance)
        {
            if (m_Wrapper.m_MainActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMainActions instance)
        {
            foreach (var item in m_Wrapper.m_MainActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MainActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MainActions @Main => new MainActions(this);
    public interface IMainActions
    {
        void OnLeftStickAxis(InputAction.CallbackContext context);
        void OnRightStickAxis(InputAction.CallbackContext context);
        void OnGrabRight(InputAction.CallbackContext context);
        void OnGrabLeft(InputAction.CallbackContext context);
        void OnUseRight(InputAction.CallbackContext context);
        void OnUseLeft(InputAction.CallbackContext context);
        void OnRightPrimary(InputAction.CallbackContext context);
        void OnRightSecondary(InputAction.CallbackContext context);
        void OnLeftPrimary(InputAction.CallbackContext context);
        void OnLeftSecondary(InputAction.CallbackContext context);
        void OnPushRightStick(InputAction.CallbackContext context);
        void OnPushLeftStick(InputAction.CallbackContext context);
        void OnMouse(InputAction.CallbackContext context);
    }
}
